# Generated by Django 4.1.6 on 2023-02-02 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_details", "0002_remove_userfooditem_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=100)),
                ("time_spent", models.CharField(max_length=100)),
                ("calories_burned_in_activity", models.CharField(max_length=100)),
                (
                    "activiy_done",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_activities",
                        to="user_details.useractivity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_activity_log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=100)),
                ("amount_consumed", models.CharField(max_length=100)),
                ("calories_consumed", models.CharField(max_length=100)),
                (
                    "food_consumed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_food_item_consumed",
                        to="user_details.userfooditem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_food_consumption",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
