# Generated by Django 4.1.6 on 2023-02-01 02:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("food_name", models.CharField(max_length=100, unique=True)),
                ("calories", models.CharField(max_length=100, unique=True)),
                ("unit", models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
