# Generated by Django 4.1.6 on 2023-02-01 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("fooditem", "0002_alter_fooditem_calories_alter_fooditem_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="fooditem",
            name="labels",
            field=models.ManyToManyField(blank=True, null=True, to="fooditem.labeltag"),
        ),
    ]
