# Generated by Django 4.1.6 on 2023-02-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fooditem", "0003_labeltag_fooditem_labels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fooditem",
            name="unit",
        ),
    ]
