# Generated by Django 4.1.6 on 2023-02-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fooditem", "0004_remove_fooditem_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="labels",
            field=models.ManyToManyField(to="fooditem.labeltag"),
        ),
    ]
