# Generated by Django 4.1.6 on 2023-02-01 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("activity_name", models.CharField(max_length=100, unique=True)),
                ("calories_burned", models.CharField(max_length=100)),
            ],
        ),
    ]
